spring.application.name=resume-parser-service
server.port=8080
server.servlet.max-file-size=10MB
server.servlet.max-request-size=10MB
logging.level.root=INFO
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
